package com.locallaunch.service;
import com.locallaunch.dto.*; import com.locallaunch.entity.*; import com.locallaunch.exception.ResourceNotFoundException; import com.locallaunch.repository.*; import org.springframework.security.core.context.SecurityContextHolder; import org.springframework.stereotype.Service; import java.util.List;
@Service public class ContactEnquiryService { private final ContactEnquiryRepository repo; private final BusinessRepository businessRepo; private final UserRepository userRepo; private final ProductRepository productRepo; public ContactEnquiryService(ContactEnquiryRepository r,BusinessRepository b,UserRepository u,ProductRepository p){repo=r;businessRepo=b;userRepo=u;productRepo=p;}
 public ContactEnquiry saveEnquiry(Long businessId,ContactEnquiry input){Business b=businessRepo.findById(businessId).orElseThrow(()->new ResourceNotFoundException("Business not found")); ContactEnquiry e=new ContactEnquiry();e.setBusiness(b);e.setCustomerName(input.getCustomerName());e.setCustomerEmail(input.getCustomerEmail());e.setMobileNumber(input.getMobileNumber());e.setMessage(input.getMessage()); if(input.getProductId()!=null){Product p=productRepo.findById(input.getProductId()).orElseThrow(()->new ResourceNotFoundException("Product not found")); if(!p.getBusiness().getId().equals(businessId)) throw new IllegalArgumentException("Product does not belong to this business");e.setProductId(p.getId());e.setProductName(p.getProductName());e.setProductPrice(p.getPrice());} return repo.save(e);}
 public List<ContactEnquiryDTO> getMyEnquiries(Long businessId){User u=user();businessRepo.findByIdAndOwnerId(businessId,u.getId()).orElseThrow(()->new ResourceNotFoundException("Business not found or access denied"));return repo.findByBusinessIdAndBusinessOwnerId(businessId,u.getId()).stream().map(this::dto).toList();}
 public ContactEnquiryDTO updateEnquiryStatus(Long id,EnquiryStatusRequest req){ContactEnquiry e=repo.findByIdAndBusinessOwnerId(id,user().getId()).orElseThrow(()->new ResourceNotFoundException("Enquiry not found or access denied"));e.setStatus(req.getStatus());return dto(repo.save(e));}
 public void deleteEnquiry(Long id){ContactEnquiry e=repo.findByIdAndBusinessOwnerId(id,user().getId()).orElseThrow(()->new ResourceNotFoundException("Enquiry not found or access denied"));repo.delete(e);}
 private ContactEnquiryDTO dto(ContactEnquiry e){return new ContactEnquiryDTO(e.getId(),e.getCustomerName(),e.getCustomerEmail(),e.getMobileNumber(),e.getMessage(),e.getStatus().name(),e.getProductId(),e.getProductName(),e.getProductPrice());}
 private User user(){String email=SecurityContextHolder.getContext().getAuthentication().getName();return userRepo.findByEmail(email).orElseThrow(()->new ResourceNotFoundException("User not found"));}
}
